[build]
command = "npm run build"
watch_dir = "."

[build.upload]
format = "service-worker"

[env.production]
name = "deep-job-researcher"
route = "deep-job-researcher.sorouri.com/*"

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 